LogFile "/var/log/clamd.log"
LogSyslog yes
LogTime yes
TCPSocket 3310
TCPAddr localhost
User clamscan

OnAccessIncludePath /tmp
OnAccessIncludePath /usr/bin
OnAccessExcludeUname clamscan
OnAccessPrevention yes
