filter {
    if [@metadata][beat] == "filebeat" and [event][dataset] == "suricata.eve" and ![suricata][eve][alert][category] {
        drop {}
    }
    if [@metadata][beat] == "filebeat" and ([process][name] == "auditbeat" or [process][name] == "filebeat" or [process][name] == "packetbeat" or [process][name] == "opensearch-dashboards") {
        drop {}
    }
    if [@metadata][beat] == "auditbeat" and [auditd][data][a0] == 10 and ([process][name] == "auditbeat" or [process][name] == "filebeat" or [process][name] == "packetbeat" or [process][name] == "opensearch-dashboards") {
        drop {}
    }
}
