input {
    beats {
        port => 5044
    }
}

output {
    if [@metadata][beat] == "winlogbeat" {
        elasticsearch {
            hosts => "https://$ELK_IP:10200"
            manage_template => false
            action => "create"
            ssl_enabled => true
            ssl_certificate_authorities => "$ES_SHARE/http_ca.crt"
            api_key => "${ES_API_KEY}"

            index => "%{[@metadata][beat]}-%{[@metadata][version]}"
            pipeline => "%{[@metadata][beat]}-%{[@metadata][version]}-routing"
        }
    } else if [@metadata][pipeline] {
        elasticsearch {
            hosts => "https://$ELK_IP:10200"
            manage_template => false
            action => "create"
            ssl_enabled => true
            ssl_certificate_authorities => "$ES_SHARE/http_ca.crt"
            api_key => "${ES_API_KEY}"

            index => "%{[@metadata][beat]}-%{[@metadata][version]}"
            pipeline => "%{[@metadata][pipeline]}"
        }
    } else if [log][file][path] == "/var/log/jj-check-daemon.json" {
        elasticsearch {
            hosts => "https://$ELK_IP:10200"
            manage_template => false
            action => "create"
            ssl_enabled => true
            ssl_certificate_authorities => "$ES_SHARE/http_ca.crt"
            api_key => "${ES_API_KEY}"

            index => "jj-check-daemon"
        }
    } else {
        elasticsearch {
            hosts => "https://$ELK_IP:10200"
            manage_template => false
            action => "create"
            ssl_enabled => true
            ssl_certificate_authorities => "$ES_SHARE/http_ca.crt"
            api_key => "${ES_API_KEY}"

            index => "%{[@metadata][beat]}-%{[@metadata][version]}"
        }
    }
}
