input { pipeline { address => wazuh } }

filter {
    if [@metadata][beat] == "filebeat" and [event][dataset] == "suricata.eve" and [suricata][eve][alert][category] == null {
        drop {}
    }
    if [@metadata][beat] == "filebeat" and ([process][name] == "auditbeat" or [process][name] == "filebeat" or [process][name] == "packetbeat" or [process][name] == "opensearch-dashboards") {
        drop {}
    }
}

output {
    if [@metadata][beat] == "winlogbeat" {
        opensearch {
            hosts => "https://$WAZUH_IP:9200"
            manage_template => false
            action => "create"
            ssl => true
            cacert => "$ES_SHARE/wazuh_http_ca.crt"
            user => "admin"
            password => "$WAZUH_PASSWORD"

            index => "%{[@metadata][beat]}-%{[@metadata][version]}"
            pipeline => "%{[@metadata][beat]}-%{[@metadata][version]}-routing"
        }
    } else if [@metadata][pipeline] {
        opensearch {
            hosts => "https://$WAZUH_IP:9200"
            manage_template => false
            action => "create"
            ssl => true
            cacert => "$ES_SHARE/wazuh_http_ca.crt"
            user => "admin"
            password => "$WAZUH_PASSWORD"

            index => "%{[@metadata][beat]}-%{[@metadata][version]}"
            pipeline => "%{[@metadata][pipeline]}"
        }
    } else if [log][file][path] == "/var/log/jj-check-daemon.json" {
        opensearch {
            hosts => "https://$WAZUH_IP:9200"
            manage_template => false
            action => "create"
            ssl => true
            cacert => "$ES_SHARE/wazuh_http_ca.crt"
            user => "admin"
            password => "$WAZUH_PASSWORD"

            index => "jj-check-daemon"
        }
    } else {
        opensearch {
            hosts => "https://$WAZUH_IP:9200"
            manage_template => false
            action => "create"
            ssl => true
            cacert => "$ES_SHARE/wazuh_http_ca.crt"
            user => "admin"
            password => "$WAZUH_PASSWORD"

            index => "%{[@metadata][beat]}-%{[@metadata][version]}"
        }
    }
}
