[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-fuse-ld=mold", "--cfg", "reqwest_unstable", "--cfg", "tracing_unstable"]

[target.'cfg(target_os = "windows")']
linker = "x86_64-w64-mingw32-gcc"
